# Generated by Django 3.0.4 on 2020-03-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arxiv_id', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('published_timestamp', models.DateTimeField()),
                ('authors', models.ManyToManyField(related_name='articles', to='scholar.Author')),
            ],
            options={
                'ordering': ['-published_timestamp'],
            },
        ),
    ]
